package net.es.oscars.pce;

import org.apache.log4j.Logger;

import net.es.oscars.logging.ErrSev;
import net.es.oscars.logging.ModuleName;
import net.es.oscars.logging.OSCARSNetLogger;
import net.es.oscars.pce.soap.gen.v06.AggregatorCreateContent;
import net.es.oscars.pce.soap.gen.v06.AggregatorModifyContent;
import net.es.oscars.pce.soap.gen.v06.AggregatorCancelContent;
import net.es.oscars.pce.soap.gen.v06.AggregatorCommitContent;
import net.es.oscars.pce.soap.gen.v06.PCECancelContent;
import net.es.oscars.pce.soap.gen.v06.PCECancelReplyContent;
import net.es.oscars.pce.soap.gen.v06.PCECommitContent;
import net.es.oscars.pce.soap.gen.v06.PCECommitReplyContent;
import net.es.oscars.pce.soap.gen.v06.PCECreateContent;
import net.es.oscars.pce.soap.gen.v06.PCEModifyContent;
import net.es.oscars.pce.soap.gen.v06.PCEModifyReplyContent;
import net.es.oscars.pce.soap.gen.v06.PCEPortType;
import net.es.oscars.pce.soap.gen.v06.PCEReplyContent;

/**
 * This class was generated by Apache CXF 2.2.5
 * Fri Sep 03 13:25:47 PDT 2010
 * Generated source version: 2.2.5
 * 
 */

/** 
* This is effectively an abstract class that handles incoming PCE messages. 
* It is implemented in the Coordinator service by:
* SimplePCEProtocolHander which implements: pceCreate, pceCommit, pceCancel and pceModify
* NullAggProtocolHandler which implements aggregatorCreate, pceCommit, pceCancel and pceModify
* NullPCEProtocolHandler which implements pceCreate, pceCommit. pceCancel and pceModify
* 
* A PCEService must implement pceCreate, may implement the other 3 messages 
*    and may use/extend SimplePCEProtocol to do so.
* @author lomax
*
*/
@javax.jws.WebService(
       serviceName = "PCEService",
       portName = "PCEPortType",
       targetNamespace = "http://oscars.es.net/OSCARS/PCE/20090922",
       endpointInterface = "net.es.oscars.pce.soap.gen.v06.PCEPortType")
@javax.xml.ws.BindingType(value ="http://www.w3.org/2003/05/soap/bindings/HTTP/")
public class PCEProtocolHandler implements PCEPortType {

   private static final Logger LOG = Logger.getLogger(PCEProtocolHandler.class.getName());

    /* (non-Javadoc)
     * @see net.es.oscars.pce.soap.gen.v06.PCEPortType#pceCommit(net.es.oscars.pce.soap.gen.v06.PCECommitContent  pceCommit )*
     */
    public void pceCommit(PCECommitContent pceCommit) { 
        OSCARSNetLogger netLogger = new OSCARSNetLogger(ModuleName.PCE, 
                        pceCommit.getMessageProperties().getGlobalTransactionId());
        LOG.error(netLogger.error("pceCommit", ErrSev.MAJOR, "Executing operation pceCommit in base class"));
        System.out.println("In PCEProtocolHandler.pceCommit");
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see net.es.oscars.pce.soap.gen.v06.PCEPortType#pceCancelReply(net.es.oscars.pce.soap.gen.v06.PCECancelReplyContent  pceCancelReply )*
     */
    public void pceCancelReply(PCECancelReplyContent pceCancelReply) { 
        OSCARSNetLogger netLogger = new OSCARSNetLogger(ModuleName.PCE, 
                pceCancelReply.getMessageProperties().getGlobalTransactionId());
        LOG.error(netLogger.error("pceCancelReply", ErrSev.MAJOR, 
                                  "Executing operation pceCancelReply in base class"));
        System.out.println("In PCEProtocolHandler.pceCancelReply");
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see net.es.oscars.pce.soap.gen.v06.PCEPortType#pceCommitReply(net.es.oscars.pce.soap.gen.v06.PCECommitReplyContent  pceCommitReply )*
     */
    public void pceCommitReply(PCECommitReplyContent pceCommitReply) { 
        OSCARSNetLogger netLogger = new OSCARSNetLogger(ModuleName.PCE, 
                pceCommitReply.getMessageProperties().getGlobalTransactionId());
        LOG.error(netLogger.error("pceCommitReply", ErrSev.MAJOR,
                                  "Executing operation pceCommitReply in base class"));
        System.out.println("In PCEProtocolHandler.pceCommitReply");
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see net.es.oscars.pce.soap.gen.v06.PCEPortType#pceCancel(net.es.oscars.pce.soap.gen.v06.PCECancelContent  pceCancel )*
     */
    public void pceCancel(PCECancelContent pceCancel) { 
        OSCARSNetLogger netLogger = new OSCARSNetLogger(ModuleName.PCE, 
                pceCancel.getMessageProperties().getGlobalTransactionId());
        LOG.error(netLogger.error("pceCancel", ErrSev.MAJOR,"Executing operation pceCancel in base class"));
        System.out.println("In PCEProtocolHandler.pceCancel");
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see net.es.oscars.pce.soap.gen.v06.PCEPortType#pceModifyReply(net.es.oscars.pce.soap.gen.v06.PCEModifyReplyContent  pceModifyReply )*
     */
    public void pceModifyReply(PCEModifyReplyContent pceModifyReply) { 
        OSCARSNetLogger netLogger = new OSCARSNetLogger(ModuleName.PCE, 
                pceModifyReply.getMessageProperties().getGlobalTransactionId());
        LOG.error(netLogger.error("pceModifyReply", 
                                   ErrSev.MAJOR,"Executing operation pceModifyReply in base class"));
        System.out.println("In PCEProtocolHandler.pceModifyReply");
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see net.es.oscars.pce.soap.gen.v06.PCEPortType#pceModify(net.es.oscars.pce.soap.gen.v06.PCEModifyContent  pceModify )*
     */
    public void pceModify(PCEModifyContent pceModify) { 
        OSCARSNetLogger netLogger = new OSCARSNetLogger(ModuleName.PCE, 
                pceModify.getMessageProperties().getGlobalTransactionId());
        LOG.error(netLogger.error("pceModify", ErrSev.MAJOR,
                                  "Executing operation pceModify in base class"));
        System.out.println("In PCEProtocolHandler.pceModify");
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see net.es.oscars.pce.soap.gen.v06.PCEPortType#aggregatorModify(net.es.oscars.pce.soap.gen.v06.AggregatorModifyContent  aggregatorModify )*
     */
    public void aggregatorModify(AggregatorModifyContent aggregatorModify) {
        OSCARSNetLogger netLogger = new OSCARSNetLogger(ModuleName.PCE, 
                aggregatorModify.getMessageProperties().getGlobalTransactionId());
        LOG.error(netLogger.error("aggregatorModify", ErrSev.MAJOR,
                                  "Executing operation aggregatorModify in base class"));
        System.out.println("In PCEProtocolHandler.aggregatorModify");
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see net.es.oscars.pce.soap.gen.v06.PCEPortType#pceReply(net.es.oscars.pce.soap.gen.v06.PCEReplyContent  pceReply )*
     */
    public void pceReply(PCEReplyContent pceReply) { 
        OSCARSNetLogger netLogger = new OSCARSNetLogger(ModuleName.PCE, 
                pceReply.getMessageProperties().getGlobalTransactionId());
        LOG.error(netLogger.error("pceReply", ErrSev.MAJOR,"Executing operation pceReply in base class"));
        System.out.println("In PCEProtocolHandler.pceReply");
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see net.es.oscars.pce.soap.gen.v06.PCEPortType#pceCreate(net.es.oscars.pce.soap.gen.v06.PCECreateContent  pceCreate )*
     */
    public void pceCreate(PCECreateContent pceCreate) { 
        OSCARSNetLogger netLogger = new OSCARSNetLogger(ModuleName.PCE, 
                pceCreate.getMessageProperties().getGlobalTransactionId());
        LOG.error(netLogger.error("pceCreate", ErrSev.MAJOR,"Executing operation pceCreate in base class"));
        System.out.println("In PCEProtocolHandler.pceCreate");
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see net.es.oscars.pce.soap.gen.v06.PCEPortType#aggregatorCreate(net.es.oscars.pce.soap.gen.v06.AggregatorCreateContent  aggregatorCreate )*
     */
    public void aggregatorCreate(AggregatorCreateContent aggregatorCreate) { 
        OSCARSNetLogger netLogger = new OSCARSNetLogger(ModuleName.PCE, 
                aggregatorCreate.getMessageProperties().getGlobalTransactionId());
        LOG.error(netLogger.error("aggregatorCreate", ErrSev.MAJOR,
                                  "Executing operation aggregatorCreate in base class"));
        System.out.println("In PCEProtocolHandler.aggregatorCreate");
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }
    public void aggregatorCommit(AggregatorCommitContent aggregatorCommit) { 
        OSCARSNetLogger netLogger = new OSCARSNetLogger(ModuleName.PCE, 
                aggregatorCommit.getMessageProperties().getGlobalTransactionId());
        LOG.error(netLogger.error("aggregatorCommit", ErrSev.MAJOR,
                                  "Executing operation aggregatorCcommit in base class"));
        System.out.println("In PCEProtocolHandler.aggregatorCommit");
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    public void aggregatorCancel(AggregatorCancelContent aggregatorCancel) { 
        OSCARSNetLogger netLogger = new OSCARSNetLogger(ModuleName.PCE, 
                aggregatorCancel.getMessageProperties().getGlobalTransactionId());
        LOG.error(netLogger.error("aggregatorCancel", ErrSev.MAJOR,
                                  "Executing operation aggregatorCancel in base class"));
        System.out.println("In PCEProtocolHandler.aggregatorCancel");
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }


}
